steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello-world
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime=nodejs16
